### ISSUE TITLE
Error if no Github profile name is set

### ISSUE THREAD

**Issue by Jopyth** [MichMich/MagicMirror-Website#5]
Got this main error, I saved the full error log, if needed.

> QueryException in Connection.php line 769: SQLSTATE[23000]: Integrity constraint violation: 1048 Column 'name' cannot be null (SQL: insert into `users` (`name`, `email`, `github_id`, `github_user`, `github_token`, `api_token`, `avatar`, `updated_at`, `created_at`) values (, *email removed*, *some number removed*, Jopyth, *token removed*, *some other token removed*, https://avatars.githubusercontent.com/u/5647772016-11-28 08:48:36v=3, 2016-11-28 08:48:36, ?))

After I set a name I was able to create an account, though, so it does not have a high priority for me.

**Comment by MichMich** [comment]
Interesting. Will look into this. Didn't know it was possible to create an account without a name. It's easy to fix, so thanks for the headsup.
